CREATE TABLE IF NOT EXISTS permission (
  id bigint NOT NULL,
  description varchar(255)
) ENGINE=InnoDB;

--ALTER TABLE public.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--    SEQUENCE NAME public.permission_id_seq
--    START WITH 1
--    INCREMENT BY 1
--    NO MINVALUE
--    NO MAXVALUE
--    CACHE 1
--);
--
--ALTER TABLE ONLY public.permission
--    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);